# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    jhon:
                        password: 123
                        roles: 'ROLE_USER'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/admin
            anonymous: ~
            http_basic: ~
            access_denied_handler: AppBundle\Security\AccessDeniedHandler

    access_control:
        - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [10.0.3.21] }
        - { path: ^/admin, roles: ROLE_NO_ACCESS }
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
